on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: maetdol/hello-world-javascript-action@v1.2
        with:
          who-to-greet: 'Maetdol'

      # id: hello 스텝에서 아웃풋을 가져온다
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
